Controllers/AssignmentsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using elearningapp.Data;
using elearningapp.Models;
using System.Web;
using LearningApp.Models;
using System.Web.Helpers;

namespace elearningapp.Controllers
{
    public class AssignmentsController : Controller
    {
        private readonly LearningAppIdentityDbContext _context;

        public AssignmentsController(LearningAppIdentityDbContext context)
        {
            _context = context;
        }

        // GET: Assignments
        public IActionResult Index(int id)
        {
            var con = (from x in _context.Courses
                     where x.Id == id
                     select x).FirstOrDefault();
            CourseDetailsViewModel concon = new CourseDetailsViewModel();

            concon.CourseTitle = con.Title;
            concon.CourseImageUrl = con.ImageUrl;
            concon.CourseDescription = con.Description;
            concon.CourseCategory = con.Category;
			string[] parts = (from x in _context.Users
							  where x.Id == con.InstructorId
							  select x.UserName).FirstOrDefault().Split('@');
			concon.InstructorName = parts[0];
            concon.LastUpdate = (from x in _context.Assignments
                                 where x.CourseId == con.Id
                                 orderby x.DueDate ascending
                                 select x.DueDate
                                 ).Take(1).FirstOrDefault();

			concon.CourseEnrollmentCount = con.EnrollmentCount;
            concon.CourseDuration = con.CourseDuration;
            concon.CourseId = con.Id;

            List<Assignments> assignments = new List<Assignments>();
            var assign = (from x in _context.Assignments
                          where x.CourseId == id
                          select x).ToList();
			assignments = assign;
            concon.Assignments = assignments;
            return View(concon);
           
        }
        // GET: Assignments/Create
        public IActionResult Create([FromQuery] int CourseId)
        {
            ViewData["CourseId"] = CourseId;
            ViewData["CourseName"] = (from x in _context.Courses
                                     where x.Id == CourseId
                                     select x.Title).FirstOrDefault();

			return View();
        }

        // POST: Assignments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CourseId,Title,Description,DueDate")] Assignments assignments)
        {
            /*var course_id = (from x in _context.Courses
                            where ViewData["CourseName"] == x.Title
                            select x.Id).FirstOrDefault();*/
            if (ModelState.IsValid)
            {
                _context.Add(assignments);
                await _context.SaveChangesAsync();
				return RedirectToAction("AssignmentList", "Users", new { assignments.CourseId });
			}
            return View(assignments);
        }

        // GET: Assignments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var course_variables = (from course in _context.Courses
                                        join assignment in _context.Assignments on course.Id equals assignment.CourseId
                                        where assignment.Id == id
                                        select course).FirstOrDefault();

            ViewData["CourseId"] = course_variables.Id;
            ViewData["CourseName"] = course_variables.Title;

            if (id == null || _context.Assignments == null)
            {
                return NotFound();
            }

            var assignments = await _context.Assignments.FindAsync(id);
            if (assignments == null)
            {
                return NotFound();
            }
            return View(assignments);
        }

        // POST: Assignments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CourseId,Title,Description,DueDate")] Assignments assignments)
        {
            var course_id = assignments.CourseId;
            if (id != assignments.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(assignments);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssignmentsExists(assignments.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("AssignmentList","Users", new { CourseId = course_id });
            }
            return RedirectToAction("AssignmentList", "Users", assignments.CourseId);
        }

        // GET: Assignments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Assignments == null)
            {
                return NotFound();
            }

            var assignments = await _context.Assignments
                .FirstOrDefaultAsync(m => m.Id == id);
            if (assignments == null)
            {
                return NotFound();
            }

            return View(assignments);
        }

        // POST: Assignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Assignments == null)
            {
                return Problem("Entity set 'LearningAppDbContext.Assignments'  is null.");
            }
            var assignments = await _context.Assignments.FindAsync(id);
            var courseid = (from x in _context.Assignments
						   where x.Id == id
						   select x.CourseId).FirstOrDefault();

			if (assignments != null)
            {
                _context.Assignments.Remove(assignments);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("AssignmentList", "Users", new {courseid });
        }

        private bool AssignmentsExists(int id)
        {
          return (_context.Assignments?.Any(e => e.Id == id)).GetValueOrDefault();
        }

		[HttpPost]
		public ActionResult CallToList()
		{
			// Get the URL of the previous page
			string previousPageUrl = Request.Headers["Referer"].ToString();

			if (!string.IsNullOrEmpty(previousPageUrl))
			{
				// Redirect back to the previous page
				return Redirect(previousPageUrl);
			}
			else
			{
				// Handle the case where there is no previous page URL
				// You can redirect to a default page or display a message to the user
				return RedirectToAction("CourseList", "UsersController"); // Example: Redirect to a default page
			}
		}
	}
}

Controllers/CoursesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using elearningapp.Data;
using elearningapp.Models;
using LearningApp.Models;
using Microsoft.AspNetCore.Authorization;
using PagedList;
using PagedList.Mvc;
using NuGet.Protocol.Core.Types;
using System.Drawing.Printing;
using Microsoft.AspNetCore.Hosting;

namespace LearningApp.Controllers
{
    public class CoursesController : Controller
    {
        private readonly LearningAppIdentityDbContext _context;
		private readonly IWebHostEnvironment _webHostEnvironment;
		public CoursesController(LearningAppIdentityDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
			_webHostEnvironment = webHostEnvironment;
		}

        // GET: Courses
        [HttpGet]
		public IActionResult Index(int p = 1)
		{
		    var headings = _context.Courses.ToPagedList(p, 6);
			return _context.Courses != null ?
			View(headings) :
              Problem("Entity set 'LearningAppIdentityDbContext.Courses'  is null.");
        }
        [HttpPost]
        public IActionResult Index(int p = 1, string searchString="")
        {
            var sortedCourses = _context.Courses
                                .Where(course => course.Title.Contains(searchString))
                                .ToList();
            var headings = sortedCourses.ToPagedList(p, 6);
            return View(headings);
        }
        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var courses = await _context.Courses
                .Include(c => c.Instructor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (courses == null)
            {
                return NotFound();
            }

            return View(courses);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
			var instructors = (from user in _context.Users
								join userRole in _context.UserRoles on user.Id equals userRole.UserId
								join role in _context.Roles on userRole.RoleId equals role.Id
								where role.Name == "Instructor"
							   select new SelectListItem
							   {
								   Value = user.Id,
								   Text = user.UserName,

							   }).ToList();
			if (User.IsInRole("Admin"))
			{
				ViewData["InstructorId"] = instructors;
			}
            else
            {
                var user_id = HttpContext.User.Claims.First().Value;
				ViewData["InstructorName"] = (from x in _context.Users where x.Id == user_id select x.UserName).FirstOrDefault();
				ViewData["InstructorId"] = user_id;

			}
				
			return View(new CourseCreateDto());
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        public async Task<IActionResult> Create( CourseCreateDto courses)
        {
            if (ModelState.IsValid)
            {
				if (courses.CourseImage != null && courses.CourseImage.Length > 0)
				{
					// Dosya yükleme courses
					string fileName = Guid.NewGuid().ToString() + Path.GetExtension(courses.CourseImage.FileName);
					string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", fileName);

					using (var stream = new FileStream(filePath, FileMode.Create))
					{
						courses.CourseImage.CopyTo(stream);
					}

					// ImageUrl'i ayarla
					courses.ImageUrl = fileName;
					courses.ImageUrl = courses.ImageUrl;
				}

				_context.Add(new Courses
                {

                    Title = courses.Title,
                    ImageUrl = courses.ImageUrl,
                    Description = courses.Description,
                    CourseDuration = courses.CourseDuration,
                    EnrollmentCount = courses.EnrollmentCount,
                    InstructorId = courses.InstructorId,
                    Category = courses.Category
                });
                await _context.SaveChangesAsync();
                return RedirectToAction("CourseList", "Users");
            }
            ViewData["InstructorId"] = new SelectList(_context.Users, "Id", "Id", courses.InstructorId);
            return View(courses);
        }
        [Authorize(Roles = "Admin, Instructor")]
        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            var instructors = (from user in _context.Users
                               join userRole in _context.UserRoles on user.Id equals userRole.UserId
                               join role in _context.Roles on userRole.RoleId equals role.Id
                               where role.Name == "Instructor"
                               select new SelectListItem
                               {
                                   Value = user.Id,
                                   Text = user.UserName,

                               }).ToList();

            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

			var courses = await _context.Courses.FindAsync(id);
            if (courses == null)
            {
                return NotFound();
            }
            CourseEditDto cto = new CourseEditDto();

			cto.Title = courses.Title;
			cto.Description = courses.Description;
			cto.CourseDuration = courses.CourseDuration;
			cto.EnrollmentCount = courses.EnrollmentCount;
			cto.InstructorId = courses.InstructorId;
            cto.ImageUrl = courses.ImageUrl;
			cto.Category = courses.Category;
            
			ViewData["InstructorData"] = instructors;
            return View(cto);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CourseEditDto courses)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var existingCourse = await _context.Courses.FindAsync(courses.Id);
					if (courses.CourseImage != null && courses.CourseImage.Length > 0 && courses.ImageUrl != existingCourse.ImageUrl)
					{
						// Dosya yükleme işlemi
						string fileName = Guid.NewGuid().ToString() + Path.GetExtension(courses.CourseImage.FileName);
						string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", fileName);

						using (var stream = new FileStream(filePath, FileMode.Create))
						{
							courses.CourseImage.CopyTo(stream);
						}

						// ImageUrl'i ayarla
						courses.ImageUrl =  fileName;
						existingCourse.ImageUrl = courses.ImageUrl;
					}
					if (existingCourse == null)
                    {
                        return NotFound();
                    }

                    // Map data from CourseDTO to existingCourse
                    existingCourse.Title = courses.Title;
                    existingCourse.Description = courses.Description;
                    existingCourse.CourseDuration = courses.CourseDuration;
                    existingCourse.EnrollmentCount = courses.EnrollmentCount;
					existingCourse.Category = courses.Category;
                    if (User.IsInRole("Admin"))
                    {
                        existingCourse.InstructorId = courses.InstructorId;
                    }
                    _context.Update(existingCourse);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CoursesExists(courses.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("CourseList","Users");
            }
            ViewData["InstructorId"] = new SelectList(_context.Users, "Id", "Id", courses.InstructorId);
            return View(courses);
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Courses == null)
            {
                return NotFound();
            }

            var courses = await _context.Courses
                .Include(c => c.Instructor)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (courses == null)
            {
                return NotFound();
            }

            return View(courses);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Courses == null)
            {
                return Problem("Entity set 'LearningAppIdentityDbContext.Courses'  is null.");
            }
            var courses = await _context.Courses.FindAsync(id);
            if (courses != null)
            {
                _context.Courses.Remove(courses);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction("CourseList", "Users");
        }

        private bool CoursesExists(int id)
        {
          return (_context.Courses?.Any(e => e.Id == id)).GetValueOrDefault();
        }
		[HttpPost]
		public async Task<IActionResult> Enroll(int courseId)
		{
			var course = await _context.Courses.FindAsync(courseId);
			var userId = _context.Users.SingleOrDefault(u => u.UserName == User.Identity.Name).Id;
			var courseID = _context.Courses.SingleOrDefault(c => c.Id == courseId).Id;

Views/Users/AssignmentList.cshtml
@model IEnumerable<elearningapp.Models.Assignments>

@{
	ViewData["Title"] = "Index";
	Layout = "_LayoutAdmin";
}


<link rel="stylesheet" href="~/css/dataTables.bootstrap.min.css">
<div class="content-wrapper">
	<div class="d-flex text-center justify-content-center mt-5">
		<h2>@ViewBag.CourseName Assignments </h2>
	</div>


	<section class="content">
		<div class="row">
			<div class="col-xs-12">
				<div class="box">
					<div class="box-header">
						<a class="btn btn-success btn-sm mt-2" asp-action="Create" asp-controller="Assignments" asp-route-CourseId="@ViewBag.CourseId">Create New Assignment</a>
					</div>


					<!-- /.box-header -->
					<div class="box-body">
						<table id="AssignmentTable" class="table table-bordered table-stripe">
							<thead>
								<tr>
									<th>
										@Html.DisplayNameFor(model => model.Title)
									</th>
									<th>
										@Html.DisplayNameFor(model => model.Description)
									</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								@foreach (var item in Model)
								{
									<tr>
										<td>
											@Html.DisplayFor(modelItem => item.Title)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.Description)
										</td>
										<td>
											@if (User.IsInRole("Admin") || User.IsInRole("Instructor"))
											{
												<a class="btn btn-primary btn-sm" asp-action="Edit" asp-controller="Assignments" asp-route-id="@item.Id">Edit </a>
											}

											@if (User.IsInRole("Admin") || User.IsInRole("Instructor"))
											{
												<a class="btn btn-danger btn-sm" asp-action="Delete" asp-controller="Assignments" asp-route-id="@item.Id">Delete</a>
											}
										</td>
									</tr>
								}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</section>

</div>

Views/Users/CourseList.cshtml
@model IEnumerable<LearningApp.Models.CourseDTO>

@{
	ViewData["Title"] = "Index";
	Layout = "_LayoutAdmin";
}


<link rel="stylesheet" href="~/css/dataTables.bootstrap.min.css">
<div class="content-wrapper">
	<div class="d-flex text-center justify-content-center mt-5">
		<h2>Course List</h2>
	</div>


	<section class="content">
		<div class="row">
			<div class="col-xs-12">
				<div class="box">
					<div class="box-header">
						<a class="btn btn-success btn-sm mt-2" asp-action="Create" asp-controller="Courses">Create New Course</a>
					</div>


					<!-- /.box-header -->
					<div class="box-body">
						<table id="CourseTable" class="table table-bordered table-stripe">
							<thead>
								<tr>
									<th>
										@Html.DisplayNameFor(model => model.Title)
									</th>
									<th>
										@Html.DisplayNameFor(model => model.Description)
									</th>
									<th>
										@Html.DisplayNameFor(model => model.InstructorId)
									</th>
									<th>
										@Html.DisplayNameFor(model => model.Category)
									</th>
									<th>
										@Html.DisplayNameFor(model => model.CourseDuration)
									</th>
									<th></th>
								</tr>
							</thead>
							<tbody>
								@foreach (var item in Model)
								{
									<tr>
										<td>
											@Html.DisplayFor(modelItem => item.Title)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.Description)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.InstructorName)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.Category)
										</td>
										<td>
											@Html.DisplayFor(modelItem => item.CourseDuration)
										</td>
										<td>
											@if (User.IsInRole("Admin") || User.IsInRole("Instructor"))
											{
												<a class="btn btn-primary btn-sm"  asp-action="Edit" asp-controller="Courses" asp-route-id="@item.Id">Edit </a>
											}

											<a class="btn btn-info btn-sm" asp-action="Details" asp-controller="Courses"  asp-route-id="@item.Id">Details </a>

											<a class="btn btn-success btn-sm" asp-action="AssignmentList" asp-controller="Users" asp-route-CourseId="@item.Id">Assignment Lists</a>
											@if (User.IsInRole("Admin"))
											{
												<a class="btn btn-danger btn-sm" asp-action="Delete" asp-controller="Courses" asp-route-id="@item.Id">Delete</a>
											}
										</td>
									</tr>
								}
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</section>

</div>

Views/Users/Create.cshtml
@model LearningApp.Models.UserCreateModel;
@{
	ViewData["Title"] = "Create User";
}
<div class="container">
	<h1>Create User</h1>
	<hr />

	<div class="row">
		<div class="col-md-4">
			<form asp-action="Create" method="post">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>

				<div class="form-group">
					<label asp-for="@Model._IdentityUser.UserName" class="control-label">Username</label>
					<input asp-for="@Model._IdentityUser.UserName" class="form-control" />
					<span asp-validation-for="@Model._IdentityUser.UserName" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="@Model._IdentityUser.Email" class="control-label">Email</label>
					<input asp-for="@Model._IdentityUser.Email" class="form-control" />
					<span asp-validation-for="@Model._IdentityUser.Email" class="text-danger"></span>
				</div>

				<div class="form-group">
					<label asp-for="@Model._IdentityUser.PasswordHash" class="control-label">Password</label>
					<input type="password" asp-for="@Model._IdentityUser.PasswordHash" class="form-control" />
					<span asp-validation-for="@Model._IdentityUser.PasswordHash" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label name="RoleName" id="RoleName" class="control-label">Role</label>
					<select name="RoleName" id="RoleName" class="form-control">
						@foreach (var item in ViewBag.RoleNames)
						{
							<option value="@item">@item</option>
						}
					</select>
				</div> 
				<!-- Add more fields as needed -->

				<div class="form-group">
					<input type="submit" class="btn btn-primary" />
				</div>
			</form>
		</div>
	</div>

	<div>
		<a asp-action="Index">Back to User List</a>
	</div>
</div>
@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}

Views/Users/Dashboard.cshtml
@model LearningApp.Models.DashboardModel;
@{
	Layout = "_LayoutAdmin";
}
<div class="content-wrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
		<h1>
			Dashboard
			<small>Control panel</small>
		</h1>
		<ol class="breadcrumb">
			<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
			<li class="active">Dashboard</li>
		</ol>
	</section>

	<!-- Main content -->
	<section class="content">
		<!-- Small boxes (Stat box) -->
		<div class="row">
			<div class="col-lg-3 col-xs-6">
				<!-- small box -->
				<div class="small-box bg-aqua">
					<div class="inner">
						<h3>@Model.InstructorCount</h3>

						<p>Instructors</p>
					</div>
					<div class="icon">
						<i class="ion ion-bag"></i>
					</div>
					<a asp-action="Index" asp-controller="Users" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
				</div>
			</div>
			<!-- ./col -->
			<div class="col-lg-3 col-xs-6">
				<!-- small box -->
				<div class="small-box bg-green">
					<div class="inner">
						<h3>@Model.StudentCount<sup style="font-size: 20px"></sup></h3>

						<p>Students</p>
					</div>
					<div class="icon">
						<i class="ion ion-stats-bars"></i>
					</div>
					<a asp-action="Index" asp-controller="Users" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>@*User listesi yönlendirme*@
				</div>
			</div>
			<!-- ./col -->
			<div class="col-lg-3 col-xs-6">
				<!-- small box -->
				<div class="small-box bg-yellow">
					<div class="inner">
						<h3>@Model.CourseCount</h3>

						<p>Courses</p>
					</div>
					<div class="icon">
						<i class="ion ion-person-add"></i>
					</div>
					<a asp-action="CourseList" asp-controller="Users" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>@*Course listesi yönlendirme*@
				</div>
			</div>
			<!-- ./col -->
			<div class="col-lg-3 col-xs-6">
				<!-- small box -->
				<div class="small-box bg-red">
					<div class="inner">
						<h3>@Model.AssignmentCount</h3>

						<p>Assignments</p>
					</div>
					<div class="icon">
						<i class="ion ion-pie-graph"></i>
					</div>
					<a href="#" class="small-box-footer"><i class="fa fa-arrow-circle-right"></i></a>
				</div>
			</div>
			<!-- ./col -->
		</div>
		<div class="row">
				<div class="col-12">
					
				</div>

		</div>
	</section>
	<!-- /.content -->
</div>
@section Scripts{
	<script></script>
}

Views/Users/Delete.cshtml
@model Microsoft.AspNetCore.Identity.IdentityUser

@{
	ViewData["Title"] = "Delete User";
}
<div class="container">
	<h1>Delete User</h1>
	<hr />

	<h3>Are you sure you want to delete this user?</h3>

	<div>
		<dl class="row">
			<dt class="col-sm-2">
				User ID
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Id)
			</dd>
			<dt class="col-sm-2">
				User Name
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.UserName)
			</dd>
			<dt class="col-sm-2">
				Email
			</dt>
			<dd class="col-sm-10">
				@Html.DisplayFor(model => model.Email)
			</dd>
		</dl>

		<form asp-action="Delete">
			<input type="hidden" asp-for="Id" />
			<input type="submit" value="Delete" class="btn btn-danger" /> |
			<a asp-action="Index">Back to User List</a>
		</form>
	</div>

</div>

Views/Users/Details.cshtml
@model Microsoft.AspNetCore.Identity.IdentityUser

@{
	ViewData["Title"] = "User Details";
}
<section class="d-flex justify-content-center align-items-center mt-5">
	<div class="row">
	<h2>User Details</h2>

		<div class="col-md-12">

		<dl class="dl-horizontal">
			<dt>
				User ID
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Id)
			</dd>
			<dt>
				User Name
			</dt>
			<dd>
				@Html.DisplayFor(model => model.UserName)
			</dd>
			<dt>
				Email
			</dt>
			<dd>
				@Html.DisplayFor(model => model.Email)
			</dd>
		</dl>
	</div>

	<div>
		<a asp-action="Edit" class="btn btn-warning btn-sm" asp-route-id="@Model.Id">Edit</a> 
		<a asp-action="Index" class="btn btn-success btn-sm">Back to User List</a>

	</div>

</div>
</section>

Views/Users/Edit.cshtml
@using LearningApp.Controllers;
@model UserWasRole

@{
	ViewData["Title"] = "Edit User";
}
<section class="d-flex justify-content-center align-items-center mt-4">
	
	<div class="row">
		<h1>Edit User</h1>
		<hr />

		<div class="col-md-12">
			<form asp-action="Edit" method="post">
				<div asp-validation-summary="ModelOnly" class="text-danger"></div>
				<input type="hidden" asp-for="Id" />
				<div class="form-group">
					<label asp-for="Username" class="control-label">Username</label>
					<input asp-for="Username" class="form-control" />
					<span asp-validation-for="Username" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="Email" class="control-label">Email</label>
					<input asp-for="Email" class="form-control" />
					<span asp-validation-for="Email" class="text-danger"></span>
				</div>
				<div class="form-group">
					<label asp-for="RoleName" class="control-label">Role</label>
					<select asp-for="RoleName" class="form-control">
						@foreach (var item in ViewBag.allroles)
						{
							<option value="@item.Text" selected="@(item.Text == Model.RoleName)" >@item.Text</option>
						}
					</select>
					<span asp-validation-for="RoleName" class="text-danger"></span>
				</div>
				<!-- Add more fields as needed -->

				<div class="form-group mt-3">
					<input type="submit" value="Save" class="btn btn-primary btn-sm" />
					<a asp-action="Index" class="btn btn-success btn-sm">Back to User List</a>
				</div>
			</form>
		</div>
	</div>

	
</section>
@section Scripts {
	@{
		await Html.RenderPartialAsync("_ValidationScriptsPartial");
	}
}